// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQKbgQutME_ANkfL7tVT_pw0xWHuO6r5A',
    appId: '1:163070316545:web:a34991fb89e94e7ea43000',
    messagingSenderId: '163070316545',
    projectId: 'mini-facebook-73145',
    authDomain: 'mini-facebook-73145.firebaseapp.com',
    storageBucket: 'mini-facebook-73145.firebasestorage.app',
    measurementId: 'G-Q8T46HB35L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwVaORocrpFeSKrZnOUgLcc4gohu0eNIk',
    appId: '1:163070316545:android:896e9c70166577b7a43000',
    messagingSenderId: '163070316545',
    projectId: 'mini-facebook-73145',
    storageBucket: 'mini-facebook-73145.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd9gZdc43cM8mm7BMiXoy2HHIArmo5q3M',
    appId: '1:163070316545:ios:4c32d4bba58d7eb8a43000',
    messagingSenderId: '163070316545',
    projectId: 'mini-facebook-73145',
    storageBucket: 'mini-facebook-73145.firebasestorage.app',
    iosClientId: '163070316545-6sksl7d17d5vs0k18n25ihrjcaq5im60.apps.googleusercontent.com',
    iosBundleId: 'com.example.yolo',
  );
}
